name: 3D Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: gajender09
          SETTING_JSON: |
            {
              "type": "night_green"
            }

      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./profile-3d-contrib
          publish_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
